# Generated by Django 2.2.2 on 2019-07-02 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('exam_creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 2, 10, 35, 21, 633707))),
                ('published', models.BooleanField(default=False)),
                ('examiners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.MyUser')),
                ('students', models.ManyToManyField(related_name='_exam_students_+', to='users.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='TakenExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('done_date', models.DateTimeField(default=datetime.datetime(2019, 7, 2, 10, 35, 21, 633707))),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Exam')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=4096)),
                ('ch1', models.CharField(max_length=255)),
                ('ch2', models.CharField(max_length=255)),
                ('ch3', models.CharField(max_length=255)),
                ('ch4', models.CharField(max_length=255)),
                ('correct_ans', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Exam')),
            ],
        ),
    ]
