# Generated by Django 2.2.2 on 2019-06-27 10:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('exam_creation_date', models.DateTimeField(default=datetime.datetime(2019, 6, 27, 13, 42, 36, 492869))),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakenExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('done_date', models.DateTimeField(default=datetime.datetime(2019, 6, 27, 13, 42, 36, 492869))),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=4096)),
                ('ch1', models.CharField(max_length=255)),
                ('ch2', models.CharField(max_length=255)),
                ('ch3', models.CharField(max_length=255)),
                ('ch4', models.CharField(max_length=255)),
                ('correct_ans', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main_app.ExaminerProfile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(related_name='_exam_students_+', to='main_app.StudentProfile'),
        ),
    ]
