# Generated by Django 2.2.2 on 2019-06-29 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_examiner', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 16, 44, 2, 271666)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main_app.MyUser'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(related_name='_exam_students_+', to='main_app.MyUser'),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 16, 44, 2, 271666)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.MyUser'),
        ),
        migrations.DeleteModel(
            name='ExaminerProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
