# Generated by Django 2.2.2 on 2019-07-03 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190702_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='published',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 13, 56, 15, 407680)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 13, 56, 15, 407680)),
        ),
    ]
