# Generated by Django 2.2.2 on 2019-07-04 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190703_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='examiners',
            new_name='examiner',
        ),
        migrations.RenameField(
            model_name='takenexam',
            old_name='students',
            new_name='student',
        ),
        migrations.AddField(
            model_name='exam',
            name='num_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 10, 18, 41, 726351)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 10, 18, 41, 727348)),
        ),
    ]
