# Generated by Django 2.2.2 on 2019-07-04 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190704_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='num_of_questions',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 10, 19, 58, 756908)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 10, 19, 58, 757904)),
        ),
    ]
