# Generated by Django 2.2.2 on 2019-07-04 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190704_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='num_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 10, 32, 52, 533315)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 10, 32, 52, 533315)),
        ),
    ]
