# Generated by Django 2.2.2 on 2019-07-08 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190708_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 12, 12, 2, 865439)),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 12, 12, 2, 865439)),
        ),
    ]
