# Generated by Django 2.2.2 on 2019-07-16 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190716_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 14, 8, 53, 212664)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 14, 8, 53, 212664)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='full_mark',
            field=models.IntegerField(),
        ),
    ]
